export const REFRESH = 30; // refresh view every 30s (base time)
export const ZOOM_LEVEL_ADJ = 5; // add 5 seconds per zoom level
export const ON_MOVE_REFRESH = 1; //refresh time to use after a movement event
export const MINIMUM_OVERRIDE_REFRESH = 5; //limit on refresh time since previous refresh, limiting repeated move refresh rate
export const REFRESH_GAME_SCORE = 15 * 60; // refresh game score every 15 minutes
export const MAX_IDLE_TIME = 15 * 60; // stop updating map after 15min idling
export const HIDDEN_SCROLLBAR_ASSUMED_WIDTH = 20;
export const SIDEBAR_WIDTH = 300;
export const CHAT_REQUEST_SCROLL_TOP = 200;
export const CHAT_SHRINKED = 60;
export const FIELD_MU_DISPLAY_AREA_ZOOM_RATIO = 0.001;
export const FIELD_MU_DISPLAY_POINT_TOLERANCE = 60
export const COLOR_SELECTED_PORTAL = '#f0f';
export const COLORS = ['#FF6600', '#0088FF', '#03DC03']; // none, res, enl
export const COLORS_LVL = ['#000', '#FECE5A', '#FFA630', '#FF7315', '#E40000', '#FD2992', '#EB26CD', '#C124E0', '#9627F4'];
export const COLORS_MOD = { VERY_RARE: '#b08cff', RARE: '#73a8ff', COMMON: '#8cffbf' };
export const MOD_TYPE = { RES_SHIELD: 'Shield', MULTIHACK: 'Multi-hack', FORCE_AMP: 'Force Amp', HEATSINK: 'Heat Sink', TURRET: 'Turret', LINK_AMPLIFIER: 'Link Amp' };
export const ACCESS_INDICATOR_COLOR = 'orange';
export const RANGE_INDICATOR_COLOR = 'red'
export const MIN_ZOOM = 3;
export const DEFAULT_ZOOM = 15;
export const DEFAULT_PORTAL_IMG = '//commondatastorage.googleapis.com/ingress.com/img/default-portal-image.png';
export const NOMINATIM = '//nominatim.openstreetmap.org/search?format=json&polygon_geojson=1&q=';
export const RESO_NRG = [0, 1000, 1500, 2000, 2500, 3000, 4000, 5000, 6000];
export const HACK_RANGE = 40; // in meters, max. distance from portal to be able to access it
export const OCTANTS = ['E', 'NE', 'N', 'NW', 'W', 'SW', 'S', 'SE'];
export const OCTANTS_ARROW = ['→', '↗', '↑', '↖', '←', '↙', '↓', '↘'];
export const DESTROY_RESONATOR = 75; //AP for destroying portal
export const DESTROY_LINK = 187; //AP for destroying link
export const DESTROY_FIELD = 750; //AP for destroying field
export const CAPTURE_PORTAL = 500; //AP for capturing a portal
export const DEPLOY_RESONATOR = 125; //AP for deploying a resonator
export const COMPLETION_BONUS = 250; //AP for deploying all resonators on portal
export const UPGRADE_ANOTHERS_RESONATOR = 65; //AP for upgrading another's resonator
export const MAX_PORTAL_LEVEL = 8;
export const MAX_RESO_PER_PLAYER = [0, 8, 4, 4, 4, 2, 2, 1, 1];
export const BASE_HACK_COOLDOWN = 300; // 5 mins - 300 seconds
export const BASE_HACK_COUNT = 4;
export const TEAM_NONE = 0;
export const TEAM_RES = 1;
export const TEAM_ENL = 2;
export const TEAM_TO_CSS = ['none', 'res', 'enl'];
export const TEAM_NAMES = ['Neutral', 'Resistance', 'Enlightened'];
